name = "Create Apocalypse Industries"
author = "Pikafear and LouisianaOtter"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0402859ed248dbbc06b58a14a812b72d5485a9c0b70ea40aeb6f02669d10642e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
