name = "Create Apocalypse Industries"
author = "Pikafear and LouisianaOtter"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a2ab65ee1b43e44489365249f8cd90c757a42631b90fb0b558cc29ea24fbfd2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
