name = "Create Apocalypse Industries"
author = "Pikafear and LouisianaOtter"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "603a718180827ef845650e068bf2e85e234bf51ad664aca12f12ee3fbbe14495"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
